spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 361776848947-sk76e3ttn8rfs6brlbn9uqmls1f5quuj.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
